_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1
auto_select_gpus: True

max_epochs: ${model.scheduler.total_epochs}

weights_summary: null
progress_bar_refresh_rate: 5
resume_from_checkpoint: null
