name: image-translation
channels:
  - defaults
  - pytorch
dependencies:
  - pytorch>=1.8.0
  - torchvision>=0.9.1
  - black           # code formatting
  - isort           # import sorting
  - flake8          # code analysis

  # --------- others --------- #
  - rich            # beautiful text formatting in terminal
  - pytest          # tests
  - sh              # for running bash commands in some tests
  - scikit-learn    # used in some callbacks
  - seaborn         # used in some callbacks
  - jupyterlab      # better jupyter notebooks
  - pip
  - pip:
    - hydra-core>=1.1.0
    - torchmetrics==0.5.1
    - pytorch-lightning==1.3.8
    - pre-commit
    - pudb
    - hydra-colorlog
    - hydra-joblib-launcher
    - hydra-optuna-sweeper
    - torch-fidelity==0.3.0
    - python-dotenv
    - wandb
