_target_: src.models.crn.Model
in_channels: ${datamodule.in_channels}
out_channels: ${datamodule.out_channels}
width: ${datamodule.width}
height: ${datamodule.height}
input_normalize: True
init_type: normal

lrG: 0.0001
b1: 0.5
b2: 0.999
optim: adam
scheduler:
  total_epochs: 400
  epoch_count: 1 # the starting epoch count
  n_epochs: 200 # number of epochs with the initial learning rate
  n_epochs_decay: 200 # number of epochs to linearly decay learning rate to zero
  lr_decay_iters: 50 # multiply by a gamma every lr_decay_iters iterations if lr_policy is step
  lr_policy: linear

eval_fid: False