_target_: src.models.spade.Model
loss_mode: hinge
in_channels: ${datamodule.in_channels}
out_channels: ${datamodule.out_channels}
width: ${datamodule.width}
height: ${datamodule.height}
input_normalize: True

init_type: normal

lrG: 0.0001
lrD: 0.0004
b1: 0
b2: 0.999
optim: adam
scheduler:
  total_epochs: 200
  epoch_count: 1 # the starting epoch count
  n_epochs: 100 # number of epochs with the initial learning rate
  n_epochs_decay: 100 # number of epochs to linearly decay learning rate to zero
  lr_decay_iters: 50 # multiply by a gamma every lr_decay_iters iterations if lr_policy is step
  lr_policy: linear

eval_fid: False